import Head from 'next/head'
import Image from 'next/image'
import PlanForm from '../components/PlanForm'
import { MuiPickersUtilsProvider } from '@material-ui/pickers'
import DateFnsUtils from '@date-io/date-fns';
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MuiPickersUtilsProvider utils={DateFnsUtils}>
        <PlanForm />
      </MuiPickersUtilsProvider>

    </>
  )
}
